# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   target: (0.72, 0.01, 0.18, 0.08, 0.01)
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet50

# Dataset
train_db_name: impact_full_imbalanced
val_db_name: impact_full_imbalanced
num_classes: 5
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 0.0001
epochs: 200
batch_size: 64
num_workers: 8

# Scheduler
scheduler: constant
